@startuml
title chat_db
entity users {
  id
  name
  mail
  phone
  icon
  workspace_id(FK)
  enter_date
  delete_date
}

entity messages {
  id
  user_id(FK)
  message
  create_date
  update_date
  thread_id(FK)
  channel_id(FK)
}

entity channels {
  id
  name
  create_date
  update_date
}

entity threads {
  id
  user_id(FK)
  channel_id(FK)
  create_date
  update_date
}

entity user_channel {
  id
  user_id(FK)
  channel_id(FK)
}

entity workspaces {
  id
  name
  create_date
  update_date
}

entity user_workspace {
  id
  user_id(FK)
  workspace_id(FK)
}

users -{ user_channel
user_channel }- channels
users -{ messages
user_workspace }- users
workspaces -{ user_workspace
messages -{ threads
channels }-  messages
@enduml
