@startuml
title db_sushi
entity "商品" {
  id
  商品名
  種別id
  金額
}

entity "種別" {
  id
  種別(セット,単品など)
}


entity "注文詳細" {
  id
  商品id
  わさび抜
  個数
}

entity "注文票" {
  id
  詳細id
  顧客id
  コメント
  合計皿数
  決済
}

entity "顧客" {
  id
  氏名
  電話番号
}

"商品" - "種別"
"注文票" - "顧客"
"注文票" -{ "注文詳細"
"注文詳細" - "商品"
@enduml
